### ISSUE TITLE
Support localhost loops when opening connection between tenants in same host

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#550]
Can we leverage current p2p dialing to call to itself? 
Does p2p support receiving connections from self as well?

 Otherwise implement an internal  call model.

**Comment by vimukthi-git** [comment]
Tried locally and with a test project and encountered error 
`dial to self attempted` 

so its not allowed right now.

https://github.com/libp2p/go-libp2p/issues/328
This is an open issue, I'm attempting to circumvent this problem by other means.

**Comment by vimukthi-git** [comment]
One very non invasive solution I found for the problem is to construct two libp2p hosts, one for external peer communication and one for local. They would run on different ports. The p2p/client/connect method would check the tenant is registered in the registry and decide to use the libp2p "local host" that we created for a local tenant or else the standard one. 

This approach I tested and it works.

**Comment by vimukthi-git** [comment]
@mikiquantum I think it doesn't make sense to have two libp2p hosts as suggested above all though it would have been a much more non invasive approach given if we still had p2p GRPC. But because I'm removing P2P GRPC and also using the context based approach, I will just make this implementation so that we call the tenant p2p event handlers(which replace grpc calls) with the tenantID in the context.
cc @lucasvo
